# __init__.py
from .haplotype import get_segment_lengths
from .get_haplotype_strings.run_plink import get_plink_haplotype_str
from .get_haplotype_strings.compare_haplotypes import compare_haplotypes
from .get_haplotype_strings.analyses_haplotype import gather_haplotypes
